__author__ = 'huangy 20160728'
import os
config: "config.yaml"
pipeDir = config['bin_dir']
rulesDir = os.path.join(os.path.expanduser(config['bin_dir']),"alignBacterial","rules")
include: os.path.join(relesDir,"checkAlignErr.rules")
include: os.path.join(relesDir,"soapAlign.rules")
include: os.path.join(relesDir,"abundance.rules")
workDir = config['work_dir']
clean_reads_list = config["subwork_dir"]["clean_reads_list"]
NCBI_Bacteria = config["NCBI_Bacteria"]
NCBI_Archaea = config["NCBI_Archaea"]
NCBI_Fungi = config["NCBI_Fungi"]
NCBI_Virus = config["NCBI_Virus"]
qsub_num = config["qsub_num"]

with open("%s/%s/clean_read"%(workDir,clean_reads_list),"r") as fq:
    with open(%s/database_list,"r") as fq2 , open("match_list","w") as fqout:
        for line in fq:
            tabs = line.strip().split("\t")
            sampleName=tabs[0]
            outDir = "%s/02.align/%s/"%(workDir,sampleName)
            for line2 in fq2:
                reference = line2.strip()
                rule align:
                    input:
                        a: tabs[1],
                        b: tabs[2],
                        r: reference
                    output:
                        o1: "%s/%s.pm"%(outDir,sampleName),
                        o2: "%s/%s.sm"%(outDir,sampleName)
                    shell: "soap -a {input.a} -b {input.b} -D {input.r}.index -M 4 -o {output.o1} -2 {output.o2} -r 2 -p 10 -m 100 -x 1000"


